ETCD_URI: "http://10.1.201.110:4001"
ETCD_PREFIX: "/NBE/_Apps/"
SQLALCHEMY_DATABASE_URI: "mysql://marco:eb320f0c@10.1.201.58:3306/dot"
SQLALCHEMY_POOL_SIZE: 100
SQLALCHEMY_POOL_TIMEOUT: 10
SQLALCHEMY_POOL_RECYCLE: 3600
DOT_URL: "http://10.1.201.99:45000"
ES_URI: "http://10.1.201.140:9200"
INFLUXDB_URI: "http://root:root@10.1.201.110:8086/NBE"

mysql:
    host: "localhost"
    port: 3306
    username: "root"
    password: ""
    db: "marco"

